export const DeliveryPlaceABI = [
  { type: "constructor", inputs: [], stateMutability: "nonpayable" },
  {
    type: "function",
    name: "closeBidOffer",
    inputs: [{ name: "_offer", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "closeBidTaker",
    inputs: [{ name: "_stock", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "initializeOwnership",
    inputs: [{ name: "_newOwner", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "paused",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "renounceOwnership",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "rescue",
    inputs: [
      { name: "to", type: "address", internalType: "address" },
      { name: "token", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setPauseStatus",
    inputs: [{ name: "pauseSatus", type: "bool", internalType: "bool" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "settleAskMaker",
    inputs: [
      { name: "_offer", type: "address", internalType: "address" },
      { name: "_settledPoints", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "settleAskTaker",
    inputs: [
      { name: "_stock", type: "address", internalType: "address" },
      { name: "_settledPoints", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "tadleFactory",
    inputs: [],
    outputs: [
      { name: "", type: "address", internalType: "contract ITadleFactory" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "CloseBidOffer",
    inputs: [
      {
        name: "_marketPlace",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "_maker",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "_offer",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "_authority",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CloseBidTaker",
    inputs: [
      {
        name: "_marketPlace",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "_maker",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "_stock",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "_authority",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "_userCollateralFee",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "_pointTokenAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      {
        name: "previousOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Paused",
    inputs: [
      {
        name: "account",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Rescue",
    inputs: [
      { name: "to", type: "address", indexed: false, internalType: "address" },
      {
        name: "token",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SetPauseStatus",
    inputs: [
      { name: "status", type: "bool", indexed: false, internalType: "bool" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SettleAskMaker",
    inputs: [
      {
        name: "_marketPlace",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "_maker",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "_offer",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "_authority",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "_settledPoints",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "_settledPointTokenAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "_makerRefundAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SettleAskTaker",
    inputs: [
      {
        name: "_marketPlace",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "_maker",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "_stock",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "_preOffer",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "_authority",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "_settledPoints",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "_settledPointTokenAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "_collateralFee",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Unpaused",
    inputs: [
      {
        name: "account",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  { type: "error", name: "AlreadyInitialized", inputs: [] },
  {
    type: "error",
    name: "FixedRatioTypeMismatch",
    inputs: [{ name: "_isSpecial", type: "bool", internalType: "bool" }],
  },
  { type: "error", name: "InsufficientRemainingPoints", inputs: [] },
  { type: "error", name: "InvaildMarketPlaceStatus", inputs: [] },
  { type: "error", name: "InvalidOfferStatus", inputs: [] },
  {
    type: "error",
    name: "InvalidOfferType",
    inputs: [
      { name: "_targetType", type: "uint8", internalType: "enum OfferType" },
      { name: "_currentType", type: "uint8", internalType: "enum OfferType" },
    ],
  },
  { type: "error", name: "InvalidPoints", inputs: [] },
  { type: "error", name: "InvalidStock", inputs: [] },
  { type: "error", name: "InvalidStockStatus", inputs: [] },
  { type: "error", name: "InvalidStockType", inputs: [] },
  { type: "error", name: "TransferFailed", inputs: [] },
  { type: "error", name: "Unauthorized", inputs: [] },
] as const;
